name: 🐛 Bug Report
description: Report a reproducible bug to help us improve.
title: "[Bug]: "
labels: [bug]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        **Thank you for taking the time to report a bug!**
        Please complete the form below to help us reproduce and fix the issue more effectively.

  - type: input
    id: environment
    attributes:
      label: Environment
      description: |
        Describe the environment where the issue occurred.
        (e.g., OS, browser, Node.js version, Docker version, etc.)
      placeholder: "Example: Ubuntu 22.04, Chrome 125, Node.js 20.3.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: |
        A clear and concise description of the issue you encountered.
      placeholder: "When I do X, Y happens instead of Z..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: |
        Provide step-by-step instructions to reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See the error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: "The app should..."
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Videos
      description: |
        If applicable, add screenshots or screen recordings to help illustrate the issue.
      placeholder: "Drag and drop or paste screenshots here."
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        If applicable, paste any relevant logs or error messages.
        Please remove sensitive information before submitting.
      render: shell
      placeholder: |
        ```
        Error: Something went wrong
            at index.js:123:45
        ```
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following before submitting:
      options:
        - label: I have searched existing issues to avoid creating duplicates.
          required: true
        - label: I have provided sufficient information to reproduce the issue.
          required: true
