name: Feature Request
description: Suggest an idea to improve this project.
title: "[Feature]: "
labels: [enhancement]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        **Thank you for suggesting a feature!**
        Please fill out this form so we can better understand your idea.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: |
        A clear and concise description of the feature you’d like to see.
      placeholder: "I would like to have..."
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: |
        Please explain why this feature would be useful.
      placeholder: "This feature would help because..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: |
        Have you considered any alternative solutions or workarounds?
      placeholder: "I have tried..."
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: |
        Add any other context or screenshots about the feature request here.
      placeholder: "Links to related issues or references..."
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Before submitting, please confirm:
      options:
        - label: I have searched existing issues to make sure this feature hasn’t been requested yet.
          required: true
        - label: I have described the feature clearly and provided supporting details.
          required: true
